# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160310_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'טיוטה'), ('a', 'ארכיון'), ('p', 'פרסם')], default='d', max_length=1),
        ),
    ]
