# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-04 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160310_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'טיוטה'), ('a', 'ארכיון'), ('t', 'עמוד'), ('p', 'פרסם')], default='d', max_length=1),
        ),
    ]
