# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'שאלה', 'verbose_name_plural': 'שאלות'},
        ),
    ]
